spring:
  application:
    name: microservice-discovery-eureka-ha
# 启用 basic 认证(true)，并设置用户名、密码
security:
  basic:
    enabled: true
  user:
    name: root
    password: xxxxxx
---
spring:
  profiles: peer1
server:
  port: 8761
# 启用认证后，注册服务需要添加登录口令
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      default-zone: http://root:xxxxxx@peer2:8762/eureka/   # 将自己注册到peer2这个Eureka上
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      default-zone: http://root:xxxxxx@peer1:8761/eureka/   # 将自己注册到peer1这个Eureka上