spring:
  application:
    name: microservice-discovery-eureka
server:
  port: 8761
eureka:
  client:
    service-url:
      default-zone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false