server:
  port: 8010
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-consumer-user
# 配置指定服务的负载均衡策略
microservice-provider-user:
  ribbon:
    # 随机
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # 轮询(默认)
    # NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
feign:
  compression:
    request:
      min-request-size: 2048
  hystrix:
    enable: true
logging:
  level:
    root: INFO
    com.zlikun.spring.feign: DEBUG